# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x0cgrpcPackage1\"\r\n\x0bvoidNoParam\"0\n\x11UpdateTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x1c\n\x0egetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"&\n\x11getAllTasksByUser\x12\x11\n\tidUsuario\x18\x01 \x01(\x03\"#\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07payload\x18\x02 \x01(\t\".\n\tTasksList\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.grpcPackage1.Task\"#\n\x12returnErrorRequest\x12\r\n\x05\x45rror\x18\x01 \x01(\t2\xde\x05\n\x05Tasks\x12\x36\n\ncreateTask\x12\x12.grpcPackage1.Task\x1a\x12.grpcPackage1.Task\"\x00\x12\x44\n\nreturnTask\x12\x19.grpcPackage1.voidNoParam\x1a\x19.grpcPackage1.voidNoParam\"\x00\x12\x42\n\x07getTask\x12\x1c.grpcPackage1.getTaskRequest\x1a\x17.grpcPackage1.TasksList\"\x00\x12\x46\n\x08getTasks\x12\x1f.grpcPackage1.getAllTasksByUser\x1a\x17.grpcPackage1.TasksList\"\x00\x12L\n\x0egetTasksByUser\x12\x1f.grpcPackage1.getAllTasksByUser\x1a\x17.grpcPackage1.TasksList\"\x00\x12\x43\n\nupdateTask\x12\x1f.grpcPackage1.UpdateTaskRequest\x1a\x12.grpcPackage1.Task\"\x00\x12O\n\x12\x64\x65leteSpecificTask\x12\x1c.grpcPackage1.getTaskRequest\x1a\x19.grpcPackage1.voidNoParam\"\x00\x12T\n\x14\x64\x65leteallTasksByUser\x12\x1f.grpcPackage1.getAllTasksByUser\x1a\x19.grpcPackage1.voidNoParam\"\x00\x12J\n\x10\x66lushTaskContent\x12\x19.grpcPackage1.voidNoParam\x1a\x19.grpcPackage1.voidNoParam\"\x00\x12\x45\n\x0breturnError\x12\x19.grpcPackage1.voidNoParam\x1a\x19.grpcPackage1.voidNoParam\"\x00\x62\x06proto3')



_VOIDNOPARAM = DESCRIPTOR.message_types_by_name['voidNoParam']
_UPDATETASKREQUEST = DESCRIPTOR.message_types_by_name['UpdateTaskRequest']
_GETTASKREQUEST = DESCRIPTOR.message_types_by_name['getTaskRequest']
_GETALLTASKSBYUSER = DESCRIPTOR.message_types_by_name['getAllTasksByUser']
_TASK = DESCRIPTOR.message_types_by_name['Task']
_TASKSLIST = DESCRIPTOR.message_types_by_name['TasksList']
_RETURNERRORREQUEST = DESCRIPTOR.message_types_by_name['returnErrorRequest']
voidNoParam = _reflection.GeneratedProtocolMessageType('voidNoParam', (_message.Message,), {
  'DESCRIPTOR' : _VOIDNOPARAM,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.voidNoParam)
  })
_sym_db.RegisterMessage(voidNoParam)

UpdateTaskRequest = _reflection.GeneratedProtocolMessageType('UpdateTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETASKREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.UpdateTaskRequest)
  })
_sym_db.RegisterMessage(UpdateTaskRequest)

getTaskRequest = _reflection.GeneratedProtocolMessageType('getTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.getTaskRequest)
  })
_sym_db.RegisterMessage(getTaskRequest)

getAllTasksByUser = _reflection.GeneratedProtocolMessageType('getAllTasksByUser', (_message.Message,), {
  'DESCRIPTOR' : _GETALLTASKSBYUSER,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.getAllTasksByUser)
  })
_sym_db.RegisterMessage(getAllTasksByUser)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.Task)
  })
_sym_db.RegisterMessage(Task)

TasksList = _reflection.GeneratedProtocolMessageType('TasksList', (_message.Message,), {
  'DESCRIPTOR' : _TASKSLIST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.TasksList)
  })
_sym_db.RegisterMessage(TasksList)

returnErrorRequest = _reflection.GeneratedProtocolMessageType('returnErrorRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETURNERRORREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage1.returnErrorRequest)
  })
_sym_db.RegisterMessage(returnErrorRequest)

_TASKS = DESCRIPTOR.services_by_name['Tasks']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOIDNOPARAM._serialized_start=29
  _VOIDNOPARAM._serialized_end=42
  _UPDATETASKREQUEST._serialized_start=44
  _UPDATETASKREQUEST._serialized_end=92
  _GETTASKREQUEST._serialized_start=94
  _GETTASKREQUEST._serialized_end=122
  _GETALLTASKSBYUSER._serialized_start=124
  _GETALLTASKSBYUSER._serialized_end=162
  _TASK._serialized_start=164
  _TASK._serialized_end=199
  _TASKSLIST._serialized_start=201
  _TASKSLIST._serialized_end=247
  _RETURNERRORREQUEST._serialized_start=249
  _RETURNERRORREQUEST._serialized_end=284
  _TASKS._serialized_start=287
  _TASKS._serialized_end=1021
# @@protoc_insertion_point(module_scope)
